# 1. OpenCv 설치(얼룩말 책 p32~34)

python 패키지는 총 4가지 종류의 패키지가 있다.   

-opencv-python   
-opencv-contrib-python   
-opencv-python-headless   
-opencv-contrib-python-headless

### 위의 네 가지 패키지는 어떻게 다른가요?

-opencv-python   
    메인 모듈만 포함된 기본 Python OpenCV 패키지.   
   
-opencv-contrib-python   
    메인 모듈과 확장 모듈이 포함된 패키지
    
-opencv-python-headless, opencv-contrib-python-headless   
    GUI 기능이 탑재되지 않은 서버 환경용(헤드리스) 패키지

### IDE는 무엇인가요? 각 IDE는 어떻게 다른가요? 주로 어떤 산업에서 쓰이나요?

-IDE(Integrated Development Environmrnt)는 통합 개발 환경의 약어로 코딩, 디버그, 컴파일, 배포 등 프로그램 개발에 관련된 모든 작업을 하나의 프로그램 안에서 처리하는 환경을 제공하는 소프트웨어다.

-PyCharm   
    코드마다 실행하는 파이썬 버전을 선택해 컴파일할 수 있다.   
    
-Eclipse   
    서로 다른 여러 프로젝트를 동시에 열어 사용하고 관리할 수 있다.   
    
-Jupyter notebook   
    텐서플로 같은 특정 라이브러리의 디버깅 및 컴파일을 시각적으로 확인할 수 있는 강력한 기능을 제공한다.

### 써본 Text Editor가 있나요? 어떤 텍스트 에디터가 가장 마음에 드나요?

-Visual Studio Code   
    다른 텍스트 에디터는 사용해 보지 않았고, Visual Studio Code만 사용해 봤는데, 파일관리나 실행을 쉽게 할 수 있어서 좋았고 무엇보다 자동완성(Tab)기능이 아주 마음에 들었다.

In [2]:
import cv2

print(cv2.__version__)

4.5.1


# 2. openCV에 대해 알아보기(얼룩말 책 p35~53)

## 1. 이미지의 크기 속성

### 왜 새로운 이미지를 불러왔을 때 오류가 나죠?

-필드나 변수에 설정된 이미지 크기에 따라 원본 이미지를 삽입하게 되는데 이때 설정된 이미지의 크기와 실제 이미지의 크기가 다르다면 액자에 이미지를 담을 수 없다. 그러므로 원본 이미지의 크기를 변경하는 함수(Image Pyramid나 Resize)를 적용한 다음 변수나 필드로 불러와 사용할 수 있다.

### 파이썬에서는 어떻게 이미지 크기를 표현하나요?(예제 2.2)

In [3]:
color = np.zeros((height, width, 3), np.uint8)
gray = np.zeros((rows, cols, 1), np.uint8)

NameError: name 'height' is not defined

## 2. 정밀도

-정밀도(Bit Depth)란 이미지가 얼마나 많은 색상을 표현할 수 있느냐를 의미한다.   
-정밀도는 색상을 표현하는 방법 중 하나다.   
-정밀도가 높을수록 많은 색상을 표현할 수 있어 데이터의 폭이 넓어지고 더 자연스로운 이미지로 표시된다.

### 색상을 표현할 때 적어도 몇 비트가 필요한가요?

-최소 8-Bit가 필요하다. 8-Bit의 경우 2의 8제곱이 되어 256가지 값을 갖게 된다. 적어도 8비트여야 유의미한 데이터를 얻게 되어 색상을 표현할 수 있게 된다.

### n.uint8이 표현할 수 있는 범위를 정수로 표현하면 얼마인가요?

-0 ~ 255의 범위

## 3. 채널

-채널은 그래픽스 이미지의 색상 정보를 담고 있다.   
-채널은 일반적으로 Red, Green, Blue와 추가로 Alpha로 구성된다.   
-이 밖에도 Hue, Saturation, Value 등의 채널도 있다.   
-색상을 표시할 때는 주로 3~4채널의 값을 사용하고 흑백 이미지를 표현할 때는 1채널을 사용한다.

### 채널은 총 몇개인가요?

-4개 혹은 7개

### 흑백 이미지를 가져올 때 왜 단일 채널을 사용해야 하나요? 3채널을 쓰면 안되나요?

-다중 채널로 사용한다면 동일한 값이 3회 반복된다.   
-이 경우 불필요한 데이터가 할당되어 연산량의 증가와 정확도의 감소를 초래한다.   
-많은 함수나 메서드에서 데이터의 양을 줄이고 정확도를 높이기 위해 입력 이미지를 변환해 단일 채널로 계산을 진행한다.

## 4. 관심 영역

-관심 영역이란 이미지상에서 관심 있는 영역을 의미한다.   
-흔히 ROI라 부르는데 Region Of Interest의 약자다.   
-이미지를 처리할 때 객체를 탐지하거나 검출하는 영역을 명확하게 관심 영역이라 지정할 수 있다.

### 1920X1280 비율의 컬러 이미지를 가져온다면 몇 개의 데이터 공간이 생성되나요?

-7,372,800개의 데이터 공간이 생성된다.

### 관심 영역을 사용해야 하는 이유를 설명한다면요?

-관심 영역을 설정하면 연산량이 줄고 정확도가 높아져서 알고리즘의 효율성이 높아진다.

## 5. 관심 채널

-관심 채널이란 이미지상에서 관심 있는 채널을 의미한다.   
-보통 COI라 부르며 Channel Of Interest의 약자다.   
-역시 이미지를 처리할 때 특정 채널을 사용해 연산을 진행하는 경우, 이부분을 관심채널이라 할 수 있다.

### 관심 채널은 어디에 활용되나요?

-특정 채널의 밝기 분포를 계산하거나 알파 혼합(Alpha Blending) 등에 활용할 수 있다.

## 6. 히스토그램

### 히스토그램이란 무엇인가요?

-히스토그램이란 도수 분포표 중 하나로 데이터의 분포를 몇 개의 구간으로 나누고 각 구간에 속하는 데이터를 시각적으로 표현한 막대그래프다.

### 히스토그램이 갖는 세 가지 중요 요소를 말하고, 이를 설명해주세요.

-빈도수(BINS): 히스토그램 그래프의 X 축 간격   
-차원 수(DIMS): 히스토그램을 분석할 이미지의 차원   
-범위(RANGE): 히스토그램 그래프의 X 축 범위

### 어떤 흑백 이미지를 가져와, 히스토그램을 출력해주세요.(예제 2.8 수행)

In [ ]:
import cv2
import numpy as np

image = cv2.imread("image.jpg")
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
result = np.zeros((image.shape[0], 256), dtype=np.uint8)

hist = cv2.calcHist([image], [0], None, [256], [0, 256])
cv2.normalize(hist, hist, 0, 255, cv2.NORM_MINMAX)

for x, y in enumerate(hist):
    cv2.line(result, (int(x), image.shape[0]), (int(x), image.shape[0] - int(y)), 255)
    
dst = np.hstack([image[:, :, 0], result])
cv2.imshow("dst", dst)
cv2.waitKey(0)
cv2.destroyAllWindows()

### 히스토그램 클래스를 분석하고, 각각의 요소를 설명해주세요. C# openCV에만 있고 python-openCV에는 없는 요소는 무엇인가요?

-mask: 이미지를 분석할 영역을 따로 설정하는 역할을 한다.
-histSize: 빈도수(BINS)를 설정하며, 히스토그램의 크기를 설정한다.   
-ranges: 범위(RANGE)를 설정한다.   
-accumulate: 히스토그램이 누적해 반영할지를 설정한다. 결과는 히스토그램(hist)에 저장된다.

-차원의 수(dims)와 균일성(uniform) 매개변수는 C#openCvSharp에서만 사용한다.

# 데이터 타입과 연산(얼룩말 책 p92~112)

## 1. numpy 데이터

### python opencv에서는 Numpy의 배열 클래스 중 ndarray를 사용합니다. 이 클래스의 중요한 요소는 무엇이 있나요?

-차원의 수(ndim), 차원의 크기(shape), 데이터 형식(dtype)이 있다.

### 예제 3.22를 수행하여 출력값을 확인하세요.

In [1]:
import numpy as np

array = np.array([[1,2,3],
                 [4,5,6]])

print(array.ndim)
print(array.shape)
print(array.dtype)

2
(2, 3)
int64


## 2. ndarray 클래스(n차원 배열)

### np.array 함수에서 C스타일과 Fortran스타일의 메모리 레이아웃의 차이를 설명해주세요.

-C에서의 다차원 배열은 가장 빠르게 변화하는 색인의 순서로 할당된다.   
-[i][j][k] 형태로 색인이 구성돼 있다면 k의 값부터 순차적으로 증가하고, 뒤의 배열 색인이 최댓값에 도달하면 그 앞의 색인이 증가하는 구조다.   
-Fortran에서는 C와 반대로 i의 값두터 순차적으로 증가하고, 앞의 배열 색인이 최댓값에 도달하면 그 뒤의 색인이 증가하는 구조다.   
-C 스타일은 행을 먼저 순차적으로 저장하며 Fortran 스타일은 열을 먼저 순차적으로 저장한다.

### 예제 3.23을 수행하여 출력값을 확인하세요.

In [ ]:
import numpy as np

array1 = np.array([[1,2,3],[4,5,6]])
array2 = np.array([1,2,3], dtype=complex, ndmin=3)
array3 = np.array(array1, copy=False)
array4 = np.array(np.mat('12;34'), subok=True)

array1[0] = [4,5,6]

print(array1)
print(array2)
print(array3)
print(type(array4))

## 배열의 개별 단위 요소에 접근하기

### Mutable 객체란 무엇인가요?

-변경이 가능한 객체

### 얕은 복사와 깊은 복사의 차이를 설명해주세요.

-얕은 복사: 복사본의 값을 바꿨을 때 원본의 값도 바뀌는 형태   
-깊은 복사: 복사본의 값을 바꿔도 원본의 값은 바뀌지 않는 형태

### 예제 3.24를 수행하고 출력값을 확인하세요. 왜 출력값이 그렇게 나오는지 설명해주세요.

In [1]:
import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([[1, 2],
                   [3, 4]])
array3 = np.array([[[1, 2],
                    [3, 4]],
                    [[5, 6],
                    [7, 8]]])

print(array1[-1])
print(array2[0][1])
print(array3[0][1][1])

3
2
4


## 배열의 블록단위 요소에 접근하기

### 예제 3.25를 수행하고 출력값을 확인하세요.

In [5]:
import numpy as np

array = np.array([[[1,2],
                  [3,4]],
                 [[5,6],
                 [7,8]]])

for i in array[0]:
    for j in i:
        if j % 2 == 0:
            print(j)

2
4


### 예제 3.26을 수행하고 출력값을 확인하세요.

In [6]:
import numpy as np

array = np.array([[1,2,3,4,5],
                 [6,7,8,9,10],
                 [11,12,13,14,15],
                 [16,17,18,19,20]])

print(array[1:3])
print(array[::2])
print(array[2:, 1::2])

[[ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 1  2  3  4  5]
 [11 12 13 14 15]]
[[12 14]
 [17 19]]


## 배열의 차원 변형

### 예제 3.27을 수행하고 출력값을 확인하세요.

In [7]:
import numpy as np

array = np.arange(12)

reshape1 = array.reshape(2,3,2)
reshape2 = np.reshape(array, (2,-1), order='F')

print(reshape1)
print(reshape2)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
[[ 0  2  4  6  8 10]
 [ 1  3  5  7  9 11]]


### numpy가이드에서 np.reshape의 구성요소를 확인하고 설명해주세요.

## 배열의 차원 확장

### 예제 3.28을 수행하고 출력값을 확인해주세요.

In [8]:
import numpy as np

array = np.arange(4)

axis1 = array[np.newaxis]
axis2 = array[:, np.newaxis]

print(axis1)
print(axis2)

[[0 1 2 3]]
[[0]
 [1]
 [2]
 [3]]


### 예제 3.29을 수행하고 출력값을 확인해주세요.

In [10]:
import numpy as np

array = np.arange(12).reshape(3,-1)

flat1 = array.flatten(order='F')
flat2 = array.ravel()

print(flat1)
print(flat2)

[ 0  4  8  1  5  9  2  6 10  3  7 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


### np.newaxis에서는 어떤 값을 줄 수 있고, 각각 어떻게 다른가요?

-대괄호 안에 np,newaxis를 지정해 배열의 차원을 증가시킨다.   
-행 부분에 지정할 경우 차원을 한 단계 추가하며, 열 부분에 지정할 경우 요소를 분해한 뒤 차원을 한 단계 추가한다.   
-행과 열 외에도 페이지 영역에도 복합적으로 사용할 수 있다.

## 배열의 병합 분리

### 예제 3.30을 수행하고 출력값을 확인해주세요.

In [12]:
import numpy as np

array1 = np.arange(6).reshape(2,3)
array2 = np.arange(6,12).reshape(2,3)

merge1 = np.stack([array1, array2], axis=0)
merge2 = np.stack([array1, array2], axis=-1)

print(merge1)
print(merge2)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[[[ 0  6]
  [ 1  7]
  [ 2  8]]

 [[ 3  9]
  [ 4 10]
  [ 5 11]]]


### 예제 3.31을 수행하고 출력값을 확인해주세요.

In [13]:
import numpy as np 

array = np.arange(10).reshape(2, 5)

detach1 = np.split(array, 2, axis=0)
detach2 = np.split(array, [2, 3], axis=1)

print(detach1)
print(detach2)

[array([[0, 1, 2, 3, 4]]), array([[5, 6, 7, 8, 9]])]
[array([[0, 1],
       [5, 6]]), array([[2],
       [7]]), array([[3, 4],
       [8, 9]])]


### 표 3.22에는 다양한 배열 함수 및 상수가 있습니다. 이 중 노드에서 자주 썼던 함수는 뭐가 있었나요? 체크해봅시다.

## 배열 연산

### 브로드캐스팅이란 무엇인가요?

-브로드 캐스팅이란 Numpy 배열에서 차원의 크기가 서로 다른 배열에서도 산술 연산을 가능하게 하는 원리다.   
-두 배열 간의 차원의 크기가 달라도 차원의 크기가 더 큰 배열에 대해 작은 배열을 여러 번 반복하지 않아도 되는 것을 의미한다.

### 형식 캐스팅이란 무엇인가요?

-형식 캐스팅이란 연산하려는 두 배열의 자료형을 비교해 표현 범위가 더 넓은 자료형을 선택하는 것을 말한다.

### 예제 3.32를 수행하고 출력값을 확인해주세요.

In [14]:
import numpy as np

array1 = np.array([1,2,3,4]).reshape(2,2)
array2 = np.array([1.5, 2.5])

add = array1 + array2

print(add)

[[2.5 4.5]
 [4.5 6.5]]


## matrix 클래스

### 예제 3.34을 수행하고 출력값을 확인해주세요.

In [15]:
import numpy as np

array1 = np.array([1,2,3,4]).reshape(2,2)
array2 = np.array([5,6,7,8]).reshape(2,2)

mat1 = np.mat(array1)
mat2 = np.mat(array2)

print(mat1.T*mat2)
print(mat1**2)

[[26 30]
 [38 44]]
[[ 7 10]
 [15 22]]
